### ISSUE TITLE
VS Code as a requirement?

### ISSUE THREAD

**Issue by andybak** [weaviate/howto-weaviate-retrieval-plugin#1]
Maybe I'm old fashioned but since when was the choice of IDE/editor a topic for a codebase itself to be involved in?

**Comment by hsm207** [comment]
I understand your perspective on the choice of IDE/editor being independent of the codebase, but let's consider this from a different angle. 

This project is a tutorial designed to help anyone, regardless of their level of development expertise, to follow along. For total beginners, deciding on an IDE can be a hurdle and by recommending a specific one, we significantly simplify their experience. This way, they can focus on learning the core concepts, rather than getting stuck on tooling choices.

For experienced developers, we trust in their ability to discern which parts of the tutorial are IDE-specific and adapt those to their preferred toolchain. We understand that seasoned developers may have preferences for certain tools due to their familiarity or specific features that align with their workflow.

Furthermore, it's worth noting that certain IDEs may provide better support for a specific programming language or framework, and therefore might be recommended or even required for working with a certain codebase. In this case, VS Code, with its support for devcontainers, made it incredibly easy to ensure everyone is developing in an identical environment. This effectively sidesteps potential complexities like setting up port forwarding, which are not the main focus of the tutorial.

Our goal here is not to impose but to guide and simplify the learning journey, especially for beginners, while giving a context where the recommended IDE adds tangible benefits to the learning and development process.

**Comment by andybak** [comment]
I think maybe it's just your wording. If you said "This tutorial assumes you're using VS Code for x reasons" then it would make more sense.

On a side note - I didn't know about devcontainers and I'm slightly disappointed they aren't yet supported in WebStorm etc.

**Comment by hsm207** [comment]
> On a side note - I didn't know about devcontainers and I'm slightly disappointed they aren't yet supported in WebStorm etc.

devcontainers is an [open spec](https://containers.dev/). It's up to the ide developers to support them. Looks like someone already made a [feature request](https://youtrack.jetbrains.com/issue/IDEA-292050/Support-for-.devcontainer) to JetBrains for this.
